# Generated by Django 4.1.4 on 2023-12-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBa', models.CharField(max_length=255)),
                ('nameEng', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBa', models.CharField(max_length=255)),
                ('nameEng', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pancake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBa', models.CharField(max_length=255)),
                ('nameEng', models.CharField(max_length=255)),
                ('dscBa', models.TextField()),
                ('dscEng', models.TextField()),
                ('image', models.ImageField(upload_to='pancakes/')),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alergens', models.ManyToManyField(blank=True, to='app.alergen')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pancake')),
            ],
        ),
        migrations.CreateModel(
            name='CreateYourOwn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBa', models.CharField(max_length=255)),
                ('nameEng', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('alergens', models.ManyToManyField(blank=True, to='app.alergen')),
            ],
        ),
    ]
