# Generated by Django 4.1.4 on 2023-12-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergen',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='alergen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createyourown',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='featuredgame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pancake',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
