# Generated by Django 4.1.4 on 2023-12-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_alergen_icon_alter_alergen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pancake',
            name='image',
            field=models.ImageField(null=True, upload_to='pancakes/'),
        ),
    ]
