# Generated by Django 4.1.4 on 2023-12-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pancake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pancake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pancakes/'),
        ),
    ]
